version: '3.9'
services:
  mongo:
    image: mongo
    ports:
            - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=ips
    networks:
        - app_network
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js    

  mongo-express:
    image: mongo-express:0.54
    ports:
          - "8081:8081"
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS}
    links:
      - mongo
    networks:
      - app_network 
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile-API
    container_name: api
    environment:
        - PYTHONPATH=/api
        - DEBUG_MODE=True
        - DB_NAME=ips
        - DB_URL=${DB_URL}
        
    command: uvicorn publicapi.main:api --host 0.0.0.0 --port 9000 --reload
    volumes:
        - ./api/publicapi:/api/publicapi/
        - ./api/models:/api/models/
        - ./api/config.py:/api/config.py
    ports:
            - 9000:9000
    networks:
      - app_network
    depends_on: 
      - mongo

#Docker Networks
networks:
    app_network:
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: 192.168.26.0/24
